### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by Clooney82** [Clooney82/MavLink_FrSkySPort#16]
I´d like to implement Milestones for major changes on the source.
What do you think about this idea?
Maybe you can also bring your ideas for milestones in.

**Comment by wolkstein** [comment]
this is a good idea. first milestone can be "stable lua telemetry for >= opentx 2.1.3. this is released since a few days, and seems to be change problems on the telemetry sensor detection side.

imo we are fine if we support opentx >= 2.1.3 and leave 2.1.1.

/g
wolke

**Comment by Clooney82** [comment]
I´m running AC3.3-rc11 and opentx 2.1.3.
For me it looks pretty good, only smaller issues.

Will add the following milestones:
- Version 1.6 (stabilize)
- Version 1.6.1 (fixes)
- ...
- Version 1.7 (LUA redesign)
- Version 1.7.x (fixes)

Any other ideas ?

for development of next version I would also create e.g. a *-next branch

**Comment by wolkstein** [comment]
ok fine,
but i only jump to AC3.3 if it is really stable. because i use pixhawk on my commercial used copter for aerials.

some questions.
sensor rpm is used for severity messages. debug output on teensy give me rpm values, also my taranis telemetry tab show me an rpm sensor. did the current used lua script located under  https://github.com/Clooney82/MavLink_FrSkySPort/blob/s-c-l-v-rc-opentx2.1/Lua_Telemetry/DisplayApmPosition/SCRIPTS/TELEMETRY/telem1.lua
play the right audiofiles?

my taranis is silent and only play the flight mode wav files.

second,
heading will only send if gps status is 3. this mean no heading infos will send if there is no gps 3d lock. i do not like this so much. imo compas heading which is used here, can be send without 3d lock on gps.

and third,
how can i get cellmin. no infos about min cell are shown on telemetry screen. also cellinfo do not work here. cellinfo is currently based on "cellmin=getValue(214)" imo this not work.. or?
and at least where is this wonderful lua screen showing all cells together. i mean this one:
![compare-gcp](https://raw.githubusercontent.com/Clooney82/MavLink_FrSkySPort/s-c-l-v-rc-opentx2.1/images/CellsScreen.jpg)

/g
wolke

**Comment by wolkstein** [comment]
ok,
got it. forgot to configure Z1 to Z6 and Cmin. RPM was also wrong here. was not RAW-.
oops :).
maybe this sensor setup can done with an "one time script" instead an default model script.

**Comment by Clooney82** [comment]
For implementing new features, please use branch: [s-c-l-v-rc-opentx2.1-next](https://github.com/Clooney82/MavLink_FrSkySPort/tree/s-c-l-v-rc-opentx2.1-next)

**Comment by fnoop** [comment]
I'd like to suggest a milestone of moving to official diydrones github home.  This is a small but significant project that contributes an important function to APM.  Craig Elder has already agreed to it, and I think it would be a great milestone to this project, what do you guys think?

**Comment by Clooney82** [comment]
like I said on diydrones, I think this is a good idea and will give us more attention.
But I think all of us have to support this, otherwise I will maybe create a own organization for this project.
