### ISSUE TITLE
Distance from home not displaying in radar

### ISSUE THREAD

**Issue by athertop** [Clooney82/MavLink_FrSkySPort#43]
Running latest 2.1 code (and with APM 3.3)
distance from home - the arrow on the radar display, even though it pointed in the correct direction for the copter heading, it stayed in the centre and the distance value under this radar stays at '0m'.

**Comment by wolkstein** [comment]
did you use the latest rev of lua script. this issue is fixed in https://github.com/Clooney82/MavLink_FrSkySPort/commit/56e56d33d5f0aabcea9d29e0e3ea2f520982219e

/g
wolke

**Comment by Clooney82** [comment]
@athertop is this still a valid issue? or is it solved?

**Comment by athertop** [comment]
@Clooney82 I have been unable to test due to the telem screen memory issues causing the screen to blank out. If the memory issues are sorted in the latest -next version then I can hopefully test this over the weekend.

**Comment by Clooney82** [comment]
@athertop, so this is only next branch related?

**Comment by athertop** [comment]
No, it's related to the release version which was current at the time I raised this. Not sure if it's resolved in the present release version now,  as I have -next branch now installed so unable to test current release version

**Comment by wolkstein** [comment]
hi, the stable version of telemetry script have mostly no memory problem. i rewrite this version from laves version with helpfully tips from opentx developer to save memory as possible and keep the garbage collector against to much work.  for example because that, i do not use dynamic objects and also make all vars script wide and not in the normal way as local function vars. also it is important that all vars, "must" initialised at script start to prevent mostly against dynamic memory allocation problems if memory use is at the limit.
@ Clooney82, removing comments from lua scripts do not change the memory problems.
see https://github.com/opentx/opentx/issues/1966 and https://github.com/opentx/opentx/issues/1870 and https://github.com/opentx/opentx/issues/1834. or search in opentx issues with commenter:wolkstein . the most lua script crashes on taranis are caused from not initialised vars and dynamic memory allocation problems. an indication for not correct initialised vars are occasional script errors. this happens if sensor data is not available and calling them returned nil. all lua math functions with nil vars ends in a script crash.

second, i use the stable script and since i update to apm3.3 i also have also the problem that the radar do not work as expected. some times it works but mostly not. think this is a problem because armed status is now not simple 1 or 0. i noticed that the flight time timer works as expected. so i am a little bit confused here why the preamheading which is needed from radar is not so clear. i think the problem is that prearmheading and pilotlat&pilotlon are overwritten because wired armed status.

/g
wolke

**Comment by athertop** [comment]
I just setup a brand new quad with new teensy 3.2 (running AUAV-X2 FC running apm 3.3.2) and have installed the 2.1 branch of your code (the Master branch, not the -next version), and All seems to work OK, except for the radar. The arrow does change direction to show the heading once armed, but it remains positioned centred in the radar screen and the distance reading remains on 0m. Strange thing I am getting though is that the GPS sensor on the Taranis (running OpenTx 2.1.6) is showing a 5-6 digit number rather than a formatted GPS position (as I am told should be the case), so not sure if the Teensy code is sending this incorrectly. Can anyone else running these software versions please check their GPS sensor in the Taranis and advise what it displays? Thanks

**Comment by athertop** [comment]
Update - issue resolved!
I managed to figure out a resolution to this issue - it is not caused by the code at all, but rather by the way the GPS sensor is added within OpenTx. I originally configured the sensors manually as per the Wiki  but adding a GPS sensor manually does not configure the sensor properly on the Taranis radio. A manually added GPS sensor will display 5-6 numeric digits instead of a Raw GPS reading, and the LUA script does not like this! Instead, the GPS sensor needs to be 'discovered' in the telemetry page on the Taranis. Doing it this way formats the sensor in a custom (GPS kind of) way.

I think it would be a great idea if the Wiki was updated to reflect this potential pitfall - Maybe add a couple of lines to explain that the suggested way to setup all the sensors is something like this:
First (with no sensors configured) do a discovery, where all the discovered sensors from the Teensy will be added; and next, edit any sensors which need to have names changed, such as Temp1 -> T1 and Temp2 -> T2, then add calculated sensors, and we're done!. Following this approach ensures that the GPS sensor is added correctly.
Thanks, Paul
