### ISSUE TITLE
USE_FLVSS_FAKE_SENSOR_DATA doesn't show the single cell value

### ISSUE THREAD

**Issue by robustini** [Clooney82/MavLink_FrSkySPort#80]
The value of the single cell remains at "0.00" on the display, while the total voltage is displayed correctly.
I enable and configure the define:

#define MAXCELLS            3
#define USE_FLVSS_FAKE_SENSOR_DATA

The "Cels" sensor show the right total battery voltage.
Please check, thanks!

**Comment by athertop** [comment]
Hey Marco - Been following your videos for years, so nice to hear from you, and thanks for the great videos - a real source of inspiration to me! A couple of things to consider for this issue - The primary one, is that you should really jump over to the newer repo for this project here: https://github.com/athertop/MavLink_FrSkySPort (the code has been far more advanced since this older Clooney repo here)

Next, to address the issue. If you have a FrSky FLVSS sensor in your system monitoring your balance connector, then leave the second of those configuration lines commented out. If however you do not have one of these sensors, then un-comment the line:

#define USE_FLVSS_FAKE_SENSOR_DATA

as this will cause the code to create an emulated FLVSS sensor, which will appear on the telemetry sensors screen as "Cels". 

Either way, following the instruction in the wiki to create a "Cmin" calculated sensor (based on this Cels sensor) will provide the minimum cell voltage to the LUA telemetry page. Details in the new wiki here (see section 6 on this link): https://github.com/athertop/MavLink_FrSkySPort/wiki/1.2.-FrSky-Taranis-Telemetry

Cheers, Paul A (athertop)
